services:
  db:
    image: ghcr.io/tursodatabase/libsql-server:latest
    platform: linux/amd64
    ports:
      - '8081:8080'
    volumes:
      - ./data/libsql:/var/lib/sqld
    environment:
      - SQLD_NODE=primary

  db-test:
    image: ghcr.io/tursodatabase/libsql-server:latest
    platform: linux/amd64
    ports:
      - '8082:8080'
    volumes:
      - ./data/libsql-test:/var/lib/sqld
    environment:
      - SQLD_NODE=primary
